Shift module
blibli-future/athens pull request #20
Opened 2017-05-22 15:24 UTC by sebastianbagya

add id into ShiftVO 
test ShiftRepository

2017-05-22 15:54 UTC, riencus requested changes
A little change that will make our code better (according to my "comparative study")

2017-05-22 15:54 UTC, arielchristianto commented on src/main/java/com/blibli/future/controller/ShiftController.java
> +    private final String PATH_WITH_ID = BASE_PATH + "/{id}";
After doing some "comparative study", I think it should be public so the test can reuse the path
`private final String ...` -> `public final String ...`

2017-05-22 15:54 UTC, arielchristianto commented on src/main/java/com/blibli/future/model/Shift.java
>  	private String id;
If we are using an Id, isn't it better to make it updated automatically? like `EmployeeAbsencePermit`?
```
@GeneratedValue(generator = "uuid")
@GenericGenerator(name = "uuid", strategy = "uuid2")
```

2017-05-22 15:54 UTC, arielchristianto commented on src/test/java/com/blibli/future/controller/ShiftControllerTest.java
> +    private final String PATH_WITH_ID = BASE_PATH + "/test";
My "comparative study" said that we don't need to write this. Just use the one declared as public in the Controller

2017-05-22 15:54 UTC, arielchristianto commented on src/test/java/com/blibli/future/controller/ShiftControllerTest.java
> +    ObjectWriter objectWriter = new ObjectMapper().writer();
Isn't this should be declared as private?

2017-05-23 08:16 UTC, sebastianbagya reviewed
already done

2017-05-23 08:16 UTC, sebastianbagya commented on src/main/java/com/blibli/future/model/Shift.java
>  	private String id;
are u sure? uuid will generate random text. I think its not good to be applied for non-transaction case.

2017-05-23 08:16 UTC, sebastianbagya commented on src/test/java/com/blibli/future/controller/ShiftControllerTest.java
> +    private final String PATH_WITH_ID = BASE_PATH + "/test";
I only make repository test. It came from previous commit.

2017-05-23 08:16 UTC, sebastianbagya commented on src/main/java/com/blibli/future/controller/ShiftController.java
> +    private final String PATH_WITH_ID = BASE_PATH + "/{id}";
I only make repository test. It came from previous commit. But thanks for review.

2017-05-23 08:16 UTC, sebastianbagya commented on src/test/java/com/blibli/future/controller/ShiftControllerTest.java
> +    ObjectWriter objectWriter = new ObjectMapper().writer();
I only make repository test. It came from previous commit. But thanks for review.

2017-05-23 08:18 UTC, sebastianbagya reviewed
please review once more

2017-05-23 08:19 UTC, merged